In [3]:
import numpy as np

# Part 1: Creating ndarrays

1. Convert the below given list of strings to an int32 NumPy array

In [ ]:
slist = ['2.5', '1.25', '0.024','2.999','1024.5']

In [ ]:
# Write your code here

x = np.array(slist)
y = x.astype(np.float)
z= y.astype(np.int32)
print(z)

[   2    1    0    2 1024]


2. Create an empty 5x5 NumPy matrix

In [5]:
empty= np.empty((5,5))

# Part 2: Operations between Arrays and Scalars

3. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3, terms are arranged indexwise, for ex

In [ ]:
sample_output = [1,3,9,27,81]

In [10]:
np.geomspace(1, 729, num=7, dtype=int)

array([  1,   3,   9,  27,  81, 242, 729])

4. Transform each of the element of the below matrix according to the below equation

    if x is an elements in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place



In [12]:
mat = [[1,2,3],[4,5,6]]

In [14]:
def my_vectorized_func(m):
    return 1/(1+(m*m))
matrix=np.array(mat)
my_vectorized_func(matrix)

array([[0.5       , 0.2       , 0.1       ],
       [0.05882353, 0.03846154, 0.02702703]])

# Part 3: Basic Indexing and Slicing

5. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1, for example

In [ ]:
output_sample = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,1,1,0],[0,1,1,1,0],[0,0,0,0,0]])
output_sample

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [17]:
x = np.zeros((5,5),dtype=int)
x[1:-1,1:-1] = 1
x

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

6. Given the 3x3x3, 3-dimensional NumPy array

In [51]:
arr = np.arange(27).reshape((3,3,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

i. Slice this matrix to contain only second and third rows, first and second columns of the given matrix.

In [ ]:
sample_output = np.array([[[3,4],[6,7]],[[12,13],[15,16]],[[21,22],[24,25]]])
sample_output

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [24]:
out_arr=arr[0:3,1:3,0:2]
out_arr

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

ii. Output a two dimensional matrix as shown below

In [ ]:
sample_output = np.array([[0,3,6],[9,12,15],[18,21,14]])
sample_output

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 14]])

In [61]:
out_arr=arr[0:1,0:3,0:1]
new_arr=np.empty((3,3),dtype=int)
new_arr[0]=np.transpose(out_arr[0])
out_arr=arr[1:2,0:3,0:1]
new_arr[1]=np.transpose(out_arr[0])
out_arr=arr[2:3,0:3,0:1]
new_arr[2]=np.transpose(out_arr[0])
new_arr
#There is a typing error last row should be as the output   

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

# Part 4: Boolean Indexing

7. Given the following array, modify it such that even values stay the same and output contains 0s instead of odd values

In [63]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
sample_output = np.array([[0,0,2],[0,4,0],[6,0,8]])
sample_output

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

In [65]:
out=arr
out[out%2==1] = 0  
out

array([[0, 0, 2],
       [0, 4, 0],
       [6, 0, 8]])

# Part 5: Fancy Indexing

8. For the given matrix, use fancy indexing to output a 2d matrix consisting all the even elements of the given matrix

In [67]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
sample_output = np.array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])
sample_output

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [69]:
col=np.array([0,2])
out=arr[:,col]
out

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

# Part 6: Expressing Conditional Logic as Array Operations



Given two following matrices, use conditional logic to replace all the odd elements of matrix A with even elements of matrix B

In [70]:
A = np.arange(9).reshape((3,3))
B = np.arange(1,10).reshape((3,3))
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
sample_output = np.array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])
sample_output

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

In [76]:
A=np.where((A %2 ==1) & (B %2 ==0), B,A )
A

array([[0, 2, 2],
       [4, 4, 6],
       [6, 8, 8]])

# Part 7: Linear Algebra

Given the following system of equations, solve for x and y using either `numpy.linalg.solve(m1,m2)` or using `inv` and `dot`

2x + 5y = 20

3x + 6y = 12

In [78]:
a=np.array([[2,5],[3,6]])
b=np.array([20,12])
np.linalg.solve(a,b)

array([-20.,  12.])